set(_CATKIN_CURRENT_PACKAGE "labbot")
set(labbot_VERSION "0.0.0")
set(labbot_MAINTAINER "Michal Fularz <michal.fularz@gmail.com>")
set(labbot_PACKAGE_FORMAT "1")
set(labbot_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "nodelet" "message_generation")
set(labbot_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "nodelet" "message_runtime")
set(labbot_BUILDTOOL_DEPENDS "catkin")
set(labbot_BUILDTOOL_EXPORT_DEPENDS )
set(labbot_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "nodelet" "message_runtime")
set(labbot_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "nodelet" "message_runtime")
set(labbot_TEST_DEPENDS )
set(labbot_DOC_DEPENDS )
set(labbot_URL_WEBSITE "")
set(labbot_URL_BUGTRACKER "")
set(labbot_URL_REPOSITORY "")
set(labbot_DEPRECATED "")