// Generated by gencpp from file labbot/msgToLabbot.msg
// DO NOT EDIT!


#ifndef LABBOT_MESSAGE_MSGTOLABBOT_H
#define LABBOT_MESSAGE_MSGTOLABBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace labbot
{
template <class ContainerAllocator>
struct msgToLabbot_
{
  typedef msgToLabbot_<ContainerAllocator> Type;

  msgToLabbot_()
    : motorRightSpeed(0.0)
    , motorLeftSpeed(0.0)  {
    }
  msgToLabbot_(const ContainerAllocator& _alloc)
    : motorRightSpeed(0.0)
    , motorLeftSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _motorRightSpeed_type;
  _motorRightSpeed_type motorRightSpeed;

   typedef float _motorLeftSpeed_type;
  _motorLeftSpeed_type motorLeftSpeed;




  typedef boost::shared_ptr< ::labbot::msgToLabbot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::labbot::msgToLabbot_<ContainerAllocator> const> ConstPtr;

}; // struct msgToLabbot_

typedef ::labbot::msgToLabbot_<std::allocator<void> > msgToLabbot;

typedef boost::shared_ptr< ::labbot::msgToLabbot > msgToLabbotPtr;
typedef boost::shared_ptr< ::labbot::msgToLabbot const> msgToLabbotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::labbot::msgToLabbot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::labbot::msgToLabbot_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace labbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'labbot': ['/home/labbot/ROS-labbot/labbot_ws/src/labbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::labbot::msgToLabbot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::labbot::msgToLabbot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::labbot::msgToLabbot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::labbot::msgToLabbot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::labbot::msgToLabbot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::labbot::msgToLabbot_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::labbot::msgToLabbot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "227e24617faca74e2a267f0d326d13ec";
  }

  static const char* value(const ::labbot::msgToLabbot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x227e24617faca74eULL;
  static const uint64_t static_value2 = 0x2a267f0d326d13ecULL;
};

template<class ContainerAllocator>
struct DataType< ::labbot::msgToLabbot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "labbot/msgToLabbot";
  }

  static const char* value(const ::labbot::msgToLabbot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::labbot::msgToLabbot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#motor speed (range: 0-80)\n\
float32 motorRightSpeed\n\
float32 motorLeftSpeed\n\
";
  }

  static const char* value(const ::labbot::msgToLabbot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::labbot::msgToLabbot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motorRightSpeed);
      stream.next(m.motorLeftSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgToLabbot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::labbot::msgToLabbot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::labbot::msgToLabbot_<ContainerAllocator>& v)
  {
    s << indent << "motorRightSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.motorRightSpeed);
    s << indent << "motorLeftSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.motorLeftSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LABBOT_MESSAGE_MSGTOLABBOT_H
