(cl:in-package labbot-msg)
(cl:export '(MOTORRIGHTINPUT-VAL
          MOTORRIGHTINPUT
          MOTORRIGHTSETPOINT-VAL
          MOTORRIGHTSETPOINT
          MOTORRIGHTOUTPUT-VAL
          MOTORRIGHTOUTPUT
          MOTORLEFTINPUT-VAL
          MOTORLEFTINPUT
          MOTORLEFTSETPOINT-VAL
          MOTORLEFTSETPOINT
          MOTORLEFTTOUTPUT-VAL
          MOTORLEFTTOUTPUT
))